---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: avarteqgmbh/a9s-utils

inputs:
- name: ssl-gateway-boshrelease
- name: semver

outputs:
- name: release-output

params:
  CF_ADMIN_USER:
  CF_ADMIN_PASSWORD:
  LOCALHOST_IP:

run: 
  path: sh
  args:
  - ../scripts/acceptance-tests.sh
