# Based on ${REPO_BASE_PATH}/shared/ops/haproxy/general-config_v6.yml

# general adjustments required to use the cfoundry-incubator/haproxy-boshrelease
# in the cloud foundry environments.
#
# manifest is here https://github.com/cloudfoundry-incubator/haproxy-boshrelease/blob/master/manifests/haproxy.yml
#
# required key's in the iaas-config.yml:
# ((iaas.ssl_gateway.ssl_gateway_instances)) - amount of ssl_gateway instances, including haproxy and /virtual_host_service_worker
# ((iaas.ssl_gateway.ssl_gateway_vm_type))  - vm_type of ssl_gateway instances, including haproxy and /virtual_host_service_worker
# ((iaas.ssl_gateway.ssl_gateway_stemcell)) - specifies stemcell, take a look how this is done in the iaas-config with the other
# deployments
# ((iaas.ssl_gateway.upstream_ips)) - gorouter ips
# ((iaas.ssl_gateway.enable_proxy_protocol)) - force flag for proxy protocol
# ((iaas.ssl_gateway.enable_https_redirect)) - force flag for http -> https redirect
# ((iaas.ssl_gateway.enable_hsts)) - force flag for hsts
# ((iaas.ssl_gateway.syslog_address)) - platform logging logstash endpoint <deployment_name>-logstash.service.dc1.((iaas.consul.domain)) 
# e.g. lod48391a-logstash.service.dc1.consul
#
# approved for: vSphere, AWS
# deployable with v1.13.0
#
# Changelog Adding local file storage for HAProxy (NM):
#   * Syslog Message Forwarding (Remove the syslog address and replace it with the default again)
#   * The log format needs to stay rfc3164 (default) to allow the syslog filter to work
#   * Configuration is done over syslog forwarder. HAProxy needs to log to /dev/log
#   * Example syslog forwarder rule: if ($programname contains 'haproxy' ) then /var/vcap/sys/log/haproxy/access.log
#   * Logrotate will be done by BOSH
#   * Ensure that you exclude haproxy in the runtime-config
#
---
# set default vm_type to small (@use config-vm-type.yml to adjust the vm_type through iaas-config)
- type: replace
  path: /instance_groups/name=ssl-gateway/vm_type?
  value: small

# amount of ssl-gateway instances
# @see iaas-config.yml
- type: replace
  path: /instance_groups/name=ssl-gateway/instances?
  value: ((iaas.ssl_gateway.ssl_gateway_instances))

# stemcell
# @see iaas-config.yml
- type: replace
  path: /instance_groups/name=ssl-gateway/stemcell?
  value: ((iaas.ssl_gateway.ssl_gateway_stemcell.os))

- type: replace
  path: /stemcells?
  value:
    - os: ((iaas.ssl_gateway.ssl_gateway_stemcell.os))
      alias: ((iaas.ssl_gateway.ssl_gateway_stemcell.alias))
      version: ((iaas.ssl_gateway.ssl_gateway_stemcell.version))

# set default azs to [z1, z2, z3] (@use config-azs.yml to adjust the azs through iaas-config)
- type: replace
  path: /instance_groups/name=ssl-gateway/azs?
  value:
  - z1
  - z2
  - z3

# LOGGING
- type: replace
  path: /instance_groups/name=ssl-gateway/jobs/name=haproxy/properties?/ha_proxy?/syslog_server?
  value: /dev/log

- type: replace
  path: /instance_groups/name=ssl-gateway/jobs/name=haproxy/properties?/ha_proxy?/log_format?
  value: rfc3164

# Debug this with 
# $DebugFile /tmp/rsyslog
# $DebugLevel 2
# in /etc/rsyslog.conf the programname can't be used because of format errors. The programname is either 1 on rfc5424 or localhost on rfc3164
- type: replace
  path: /instance_groups/name=ssl-gateway/jobs/-
  value:
    name: syslog_forwarder
    release: syslog
    properties:
      syslog:
        address: ((iaas.ssl_gateway.syslog_address))
        custom_rule: "if ($msg startswith ' haproxy') then  /var/vcap/sys/log/haproxy/access.log"
        forward_files: false

- type: replace
  path: /releases/-
  value:
    name: syslog
    version: latest
# END LOGGING

# configure cipherscan compliant with the official mozilla recommendation
# https://ssl-config.mozilla.org/#server=haproxy&version=1.9.15&config=intermediate&openssl=1.0.2d&ocsp=false&guideline=5.6
# Assuming openssl v1.28 (haproxy2.2.5 and openssl 1.0.2g)
- type: replace
  path: /instance_groups/name=ssl-gateway/jobs/name=haproxy/properties?/ha_proxy?/ssl_ciphers?
  value: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"

# disable TLS v1.0
- type: replace
  path: /instance_groups/name=ssl-gateway/jobs/name=haproxy/properties?/ha_proxy?/disable_tls_10?
  value: true

# disable TLS v1.1
- type: replace
  path: /instance_groups/name=ssl-gateway/jobs/name=haproxy/properties?/ha_proxy?/disable_tls_11?
  value: true


# active health checks to gorouters (<go_router_ip>:8080/health)
- type: replace
  path: /instance_groups/name=ssl-gateway/jobs/name=haproxy/properties/ha_proxy/backend_use_http_health?
  value: true

# haproxy health endpoint (<ha_proxy_ip>:4443/health)
# configure this as health check endpoint in your IaaS loadbalancer
- type: replace
  path: /instance_groups/name=ssl-gateway/jobs/name=haproxy/properties/ha_proxy/enable_health_check_http?
  value: true

- type: replace
  path: /instance_groups/name=ssl-gateway/jobs/name=haproxy/properties/ha_proxy/health_check_port?
  value: 4443

# gorouter https backend
# @see config.yml
- type: replace
  path: /instance_groups/name=ssl-gateway/jobs/name=haproxy/properties/ha_proxy/backend_servers?
  value: ((iaas.ssl_gateway.upstream_ips))

- type: replace
  path: /instance_groups/name=ssl-gateway/jobs/name=haproxy/properties/ha_proxy/backend_port?
  value: 443

- type: replace
  path: /instance_groups/name=ssl-gateway/jobs/name=haproxy/properties/ha_proxy/backend_ssl?
  value: "verify"

# add default certificate for tcp backends
- type: replace
  path: /instance_groups/name=ssl-gateway/jobs/name=haproxy/properties/ha_proxy/backend_ca_file?
  value: |
    ((/overbosh/cf/router_ssl.ca))

# force flag for proxy protocol
# @see config.yml
- type: replace
  path: /instance_groups/name=ssl-gateway/jobs/name=haproxy/properties/ha_proxy/accept_proxy?
  value: ((iaas.ssl_gateway.enable_proxy_protocol))

# force flag for http -> https redirect (301 moved permanently)
# @see config.yml
- type: replace
  path: /instance_groups/name=ssl-gateway/jobs/name=haproxy/properties/ha_proxy/https_redirect_all?
  value: ((iaas.ssl_gateway.enable_https_redirect))

# increase HAProxy keepalive timeout
- type: replace
  path: /instance_groups/name=ssl-gateway/jobs/name=haproxy/properties/ha_proxy/keepalive_timeout?
  value: 300

# increase HAProxy server timeout
- type: replace
  path: /instance_groups/name=ssl-gateway/jobs/name=haproxy/properties/ha_proxy/server_timeout?
  value: 300

# increase HAProxy client timeout
- type: replace
  path: /instance_groups/name=ssl-gateway/jobs/name=haproxy/properties/ha_proxy/client_timeout?
  value: 300

# enable HSTS
- type: replace
  path: /instance_groups/name=ssl-gateway/jobs/name=haproxy/properties/ha_proxy/hsts_enable?
  value: ((iaas.ssl_gateway.enable_hsts))
